info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local
    datasource:
        # Change the maximum pool size if your application needs it.
        hikari.maximumPoolSize: 3

logging:
    level:
        ske.aurora: INFO
        no.skatteetaten: INFO
        org:
            springframework: WARN
            apache.catalina: WARN
            hibernate: WARN

---
spring:
    profiles: local
    datasource:
        url: ${refapp.datasource.url:jdbc:oracle:thin:@host:port:path}
        username: ${refapp.datasource.username:username}
        password: ${refapp.datasource.password:password}


s3:
    buckets:
        default:
            serviceEndpoint: "http://172.20.0.2:9000"
            accessKey: "minio"
            secretKey: "miniosecret"
            objectPrefix: "default"
            bucketRegion: "us-east-1"
            bucketName: "default"



management:
    server.port: 8081


logging:
    pattern:
        console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"