info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local
    datasource:
        # Change the maximum pool size if your application needs it.
        hikari.maximumPoolSize: 3
        driver-class-name: org.postgresql.Driver

logging:
    level:
        ske.aurora: INFO
        no.skatteetaten: INFO
        org:
            springframework: WARN
            apache.catalina: WARN
            hibernate: WARN

---
spring:
    profiles: local
    datasource:
        url: ${refapp.datasource.url:jdbc:postgresql://localhost:5432/refapp}
        username: ${refapp.datasource.username:postgres}
        password: ${refapp.datasource.password:postgres}


s3:
    buckets:
        default:
            serviceEndpoint: "http://localhost:9000"
            accessKey: "minio"
            secretKey: "miniosecret"
            objectPrefix: "default"
            bucketRegion: "us-east-1"
            bucketName: "default"



management:
    server.port: 8081


logging:
    pattern:
        console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"